---
abstract: 'Middleware that handles the Yada Yada operator'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  HTTP::Request::Common: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Acme-YadaYada
requires:
  Plack: 0
  Try::Tiny: 0
  parent: 0
  perl: 5.12.0
resources:
  bugtracker: http://github.com/hoelzro/plack-middleware-acme-yadayada/issues
  homepage: http://github.com/hoelzro/plack-middleware-acme-yadayada
  repository: http://github.com/hoelzro/plack-middleware-acme-yadayada
version: 0.01
